// This file is autogenerated. Do not modify directly.
package hilighter

func Reset(str string, args ...interface{}) string {
	return modify("reset", str, args...)
}

func Normal(str string, args ...interface{}) string {
	return modify("normal", str, args...)
}

func Bold(str string, args ...interface{}) string {
	return modify("bold", str, args...)
}

func NoBold(str string, args ...interface{}) string {
	return modify("no_bold", str, args...)
}

func Dim(str string, args ...interface{}) string {
	return modify("dim", str, args...)
}

func NoDim(str string, args ...interface{}) string {
	return modify("no_dim", str, args...)
}

func Faint(str string, args ...interface{}) string {
	return modify("faint", str, args...)
}

func NoFaint(str string, args ...interface{}) string {
	return modify("no_faint", str, args...)
}

func Italic(str string, args ...interface{}) string {
	return modify("italic", str, args...)
}

func NoItalic(str string, args ...interface{}) string {
	return modify("no_italic", str, args...)
}

func Underline(str string, args ...interface{}) string {
	return modify("underline", str, args...)
}

func NoUnderline(str string, args ...interface{}) string {
	return modify("no_underline", str, args...)
}

func Blink(str string, args ...interface{}) string {
	return modify("blink", str, args...)
}

func NoBlink(str string, args ...interface{}) string {
	return modify("no_blink", str, args...)
}

func BlinkSlow(str string, args ...interface{}) string {
	return modify("blink_slow", str, args...)
}

func NoBlinkSlow(str string, args ...interface{}) string {
	return modify("no_blink_slow", str, args...)
}

func BlinkRapid(str string, args ...interface{}) string {
	return modify("blink_rapid", str, args...)
}

func NoBlinkRapid(str string, args ...interface{}) string {
	return modify("no_blink_rapid", str, args...)
}

func Inverse(str string, args ...interface{}) string {
	return modify("inverse", str, args...)
}

func NoInverse(str string, args ...interface{}) string {
	return modify("no_inverse", str, args...)
}

func Negative(str string, args ...interface{}) string {
	return modify("negative", str, args...)
}

func NoNegative(str string, args ...interface{}) string {
	return modify("no_negative", str, args...)
}

func Swap(str string, args ...interface{}) string {
	return modify("swap", str, args...)
}

func NoSwap(str string, args ...interface{}) string {
	return modify("no_swap", str, args...)
}

func Hide(str string, args ...interface{}) string {
	return modify("hide", str, args...)
}

func NoHide(str string, args ...interface{}) string {
	return modify("no_hide", str, args...)
}

func Conceal(str string, args ...interface{}) string {
	return modify("conceal", str, args...)
}

func NoConceal(str string, args ...interface{}) string {
	return modify("no_conceal", str, args...)
}

func CrossedOut(str string, args ...interface{}) string {
	return modify("crossed_out", str, args...)
}

func NoCrossedOut(str string, args ...interface{}) string {
	return modify("no_crossed_out", str, args...)
}

func Strikethrough(str string, args ...interface{}) string {
	return modify("strikethrough", str, args...)
}

func NoStrikethrough(str string, args ...interface{}) string {
	return modify("no_strikethrough", str, args...)
}

func Fraktur(str string, args ...interface{}) string {
	return modify("fraktur", str, args...)
}

func NoFraktur(str string, args ...interface{}) string {
	return modify("no_fraktur", str, args...)
}
