// Code generated by scripts/generate_go_funcs; DO NOT EDIT.
package hilighter

import "fmt"

// Black will Hilight() the provided string with the
// specified ANSI code.
func Black(str string) string {
	return Hilight("black", str)
}

// Blackf wraps fmt.Sprintf() and Black.
func Blackf(format string, args ...any) string {
	return Black(fmt.Sprintf(format, args...))
}

// OnBlack will Hilight() the provided string with the
// specified ANSI code.
func OnBlack(str string) string {
	return Hilight("onblack", str)
}

// OnBlackf wraps fmt.Sprintf() and OnBlack.
func OnBlackf(format string, args ...any) string {
	return OnBlack(fmt.Sprintf(format, args...))
}

// LightBlack will Hilight() the provided string with the
// specified ANSI code.
func LightBlack(str string) string {
	return Hilight("lightblack", str)
}

// LightBlackf wraps fmt.Sprintf() and LightBlack.
func LightBlackf(format string, args ...any) string {
	return LightBlack(fmt.Sprintf(format, args...))
}

// OnLightBlack will Hilight() the provided string with the
// specified ANSI code.
func OnLightBlack(str string) string {
	return Hilight("onlightblack", str)
}

// OnLightBlackf wraps fmt.Sprintf() and OnLightBlack.
func OnLightBlackf(format string, args ...any) string {
	return OnLightBlack(fmt.Sprintf(format, args...))
}

// Red will Hilight() the provided string with the
// specified ANSI code.
func Red(str string) string {
	return Hilight("red", str)
}

// Redf wraps fmt.Sprintf() and Red.
func Redf(format string, args ...any) string {
	return Red(fmt.Sprintf(format, args...))
}

// OnRed will Hilight() the provided string with the
// specified ANSI code.
func OnRed(str string) string {
	return Hilight("onred", str)
}

// OnRedf wraps fmt.Sprintf() and OnRed.
func OnRedf(format string, args ...any) string {
	return OnRed(fmt.Sprintf(format, args...))
}

// LightRed will Hilight() the provided string with the
// specified ANSI code.
func LightRed(str string) string {
	return Hilight("lightred", str)
}

// LightRedf wraps fmt.Sprintf() and LightRed.
func LightRedf(format string, args ...any) string {
	return LightRed(fmt.Sprintf(format, args...))
}

// OnLightRed will Hilight() the provided string with the
// specified ANSI code.
func OnLightRed(str string) string {
	return Hilight("onlightred", str)
}

// OnLightRedf wraps fmt.Sprintf() and OnLightRed.
func OnLightRedf(format string, args ...any) string {
	return OnLightRed(fmt.Sprintf(format, args...))
}

// Green will Hilight() the provided string with the
// specified ANSI code.
func Green(str string) string {
	return Hilight("green", str)
}

// Greenf wraps fmt.Sprintf() and Green.
func Greenf(format string, args ...any) string {
	return Green(fmt.Sprintf(format, args...))
}

// OnGreen will Hilight() the provided string with the
// specified ANSI code.
func OnGreen(str string) string {
	return Hilight("ongreen", str)
}

// OnGreenf wraps fmt.Sprintf() and OnGreen.
func OnGreenf(format string, args ...any) string {
	return OnGreen(fmt.Sprintf(format, args...))
}

// LightGreen will Hilight() the provided string with the
// specified ANSI code.
func LightGreen(str string) string {
	return Hilight("lightgreen", str)
}

// LightGreenf wraps fmt.Sprintf() and LightGreen.
func LightGreenf(format string, args ...any) string {
	return LightGreen(fmt.Sprintf(format, args...))
}

// OnLightGreen will Hilight() the provided string with the
// specified ANSI code.
func OnLightGreen(str string) string {
	return Hilight("onlightgreen", str)
}

// OnLightGreenf wraps fmt.Sprintf() and OnLightGreen.
func OnLightGreenf(format string, args ...any) string {
	return OnLightGreen(fmt.Sprintf(format, args...))
}

// Yellow will Hilight() the provided string with the
// specified ANSI code.
func Yellow(str string) string {
	return Hilight("yellow", str)
}

// Yellowf wraps fmt.Sprintf() and Yellow.
func Yellowf(format string, args ...any) string {
	return Yellow(fmt.Sprintf(format, args...))
}

// OnYellow will Hilight() the provided string with the
// specified ANSI code.
func OnYellow(str string) string {
	return Hilight("onyellow", str)
}

// OnYellowf wraps fmt.Sprintf() and OnYellow.
func OnYellowf(format string, args ...any) string {
	return OnYellow(fmt.Sprintf(format, args...))
}

// LightYellow will Hilight() the provided string with the
// specified ANSI code.
func LightYellow(str string) string {
	return Hilight("lightyellow", str)
}

// LightYellowf wraps fmt.Sprintf() and LightYellow.
func LightYellowf(format string, args ...any) string {
	return LightYellow(fmt.Sprintf(format, args...))
}

// OnLightYellow will Hilight() the provided string with the
// specified ANSI code.
func OnLightYellow(str string) string {
	return Hilight("onlightyellow", str)
}

// OnLightYellowf wraps fmt.Sprintf() and OnLightYellow.
func OnLightYellowf(format string, args ...any) string {
	return OnLightYellow(fmt.Sprintf(format, args...))
}

// Blue will Hilight() the provided string with the
// specified ANSI code.
func Blue(str string) string {
	return Hilight("blue", str)
}

// Bluef wraps fmt.Sprintf() and Blue.
func Bluef(format string, args ...any) string {
	return Blue(fmt.Sprintf(format, args...))
}

// OnBlue will Hilight() the provided string with the
// specified ANSI code.
func OnBlue(str string) string {
	return Hilight("onblue", str)
}

// OnBluef wraps fmt.Sprintf() and OnBlue.
func OnBluef(format string, args ...any) string {
	return OnBlue(fmt.Sprintf(format, args...))
}

// LightBlue will Hilight() the provided string with the
// specified ANSI code.
func LightBlue(str string) string {
	return Hilight("lightblue", str)
}

// LightBluef wraps fmt.Sprintf() and LightBlue.
func LightBluef(format string, args ...any) string {
	return LightBlue(fmt.Sprintf(format, args...))
}

// OnLightBlue will Hilight() the provided string with the
// specified ANSI code.
func OnLightBlue(str string) string {
	return Hilight("onlightblue", str)
}

// OnLightBluef wraps fmt.Sprintf() and OnLightBlue.
func OnLightBluef(format string, args ...any) string {
	return OnLightBlue(fmt.Sprintf(format, args...))
}

// Magenta will Hilight() the provided string with the
// specified ANSI code.
func Magenta(str string) string {
	return Hilight("magenta", str)
}

// Magentaf wraps fmt.Sprintf() and Magenta.
func Magentaf(format string, args ...any) string {
	return Magenta(fmt.Sprintf(format, args...))
}

// OnMagenta will Hilight() the provided string with the
// specified ANSI code.
func OnMagenta(str string) string {
	return Hilight("onmagenta", str)
}

// OnMagentaf wraps fmt.Sprintf() and OnMagenta.
func OnMagentaf(format string, args ...any) string {
	return OnMagenta(fmt.Sprintf(format, args...))
}

// LightMagenta will Hilight() the provided string with the
// specified ANSI code.
func LightMagenta(str string) string {
	return Hilight("lightmagenta", str)
}

// LightMagentaf wraps fmt.Sprintf() and LightMagenta.
func LightMagentaf(format string, args ...any) string {
	return LightMagenta(fmt.Sprintf(format, args...))
}

// OnLightMagenta will Hilight() the provided string with the
// specified ANSI code.
func OnLightMagenta(str string) string {
	return Hilight("onlightmagenta", str)
}

// OnLightMagentaf wraps fmt.Sprintf() and OnLightMagenta.
func OnLightMagentaf(format string, args ...any) string {
	return OnLightMagenta(fmt.Sprintf(format, args...))
}

// Cyan will Hilight() the provided string with the
// specified ANSI code.
func Cyan(str string) string {
	return Hilight("cyan", str)
}

// Cyanf wraps fmt.Sprintf() and Cyan.
func Cyanf(format string, args ...any) string {
	return Cyan(fmt.Sprintf(format, args...))
}

// OnCyan will Hilight() the provided string with the
// specified ANSI code.
func OnCyan(str string) string {
	return Hilight("oncyan", str)
}

// OnCyanf wraps fmt.Sprintf() and OnCyan.
func OnCyanf(format string, args ...any) string {
	return OnCyan(fmt.Sprintf(format, args...))
}

// LightCyan will Hilight() the provided string with the
// specified ANSI code.
func LightCyan(str string) string {
	return Hilight("lightcyan", str)
}

// LightCyanf wraps fmt.Sprintf() and LightCyan.
func LightCyanf(format string, args ...any) string {
	return LightCyan(fmt.Sprintf(format, args...))
}

// OnLightCyan will Hilight() the provided string with the
// specified ANSI code.
func OnLightCyan(str string) string {
	return Hilight("onlightcyan", str)
}

// OnLightCyanf wraps fmt.Sprintf() and OnLightCyan.
func OnLightCyanf(format string, args ...any) string {
	return OnLightCyan(fmt.Sprintf(format, args...))
}

// White will Hilight() the provided string with the
// specified ANSI code.
func White(str string) string {
	return Hilight("white", str)
}

// Whitef wraps fmt.Sprintf() and White.
func Whitef(format string, args ...any) string {
	return White(fmt.Sprintf(format, args...))
}

// OnWhite will Hilight() the provided string with the
// specified ANSI code.
func OnWhite(str string) string {
	return Hilight("onwhite", str)
}

// OnWhitef wraps fmt.Sprintf() and OnWhite.
func OnWhitef(format string, args ...any) string {
	return OnWhite(fmt.Sprintf(format, args...))
}

// LightWhite will Hilight() the provided string with the
// specified ANSI code.
func LightWhite(str string) string {
	return Hilight("lightwhite", str)
}

// LightWhitef wraps fmt.Sprintf() and LightWhite.
func LightWhitef(format string, args ...any) string {
	return LightWhite(fmt.Sprintf(format, args...))
}

// OnLightWhite will Hilight() the provided string with the
// specified ANSI code.
func OnLightWhite(str string) string {
	return Hilight("onlightwhite", str)
}

// OnLightWhitef wraps fmt.Sprintf() and OnLightWhite.
func OnLightWhitef(format string, args ...any) string {
	return OnLightWhite(fmt.Sprintf(format, args...))
}

// Default will Hilight() the provided string with the
// specified ANSI code.
func Default(str string) string {
	return Hilight("default", str)
}

// Defaultf wraps fmt.Sprintf() and Default.
func Defaultf(format string, args ...any) string {
	return Default(fmt.Sprintf(format, args...))
}

// OnDefault will Hilight() the provided string with the
// specified ANSI code.
func OnDefault(str string) string {
	return Hilight("ondefault", str)
}

// OnDefaultf wraps fmt.Sprintf() and OnDefault.
func OnDefaultf(format string, args ...any) string {
	return OnDefault(fmt.Sprintf(format, args...))
}

// Reset will Hilight() the provided string with the
// specified ANSI code.
func Reset(str string) string {
	return Hilight("reset", str)
}

// Resetf wraps fmt.Sprintf() and Reset.
func Resetf(format string, args ...any) string {
	return Reset(fmt.Sprintf(format, args...))
}

// Normal will Hilight() the provided string with the
// specified ANSI code.
func Normal(str string) string {
	return Hilight("normal", str)
}

// Normalf wraps fmt.Sprintf() and Normal.
func Normalf(format string, args ...any) string {
	return Normal(fmt.Sprintf(format, args...))
}

// Bold will Hilight() the provided string with the
// specified ANSI code.
func Bold(str string) string {
	return Hilight("bold", str)
}

// Boldf wraps fmt.Sprintf() and Bold.
func Boldf(format string, args ...any) string {
	return Bold(fmt.Sprintf(format, args...))
}

// NoBold will Hilight() the provided string with the
// specified ANSI code.
func NoBold(str string) string {
	return Hilight("nobold", str)
}

// NoBoldf wraps fmt.Sprintf() and NoBold.
func NoBoldf(format string, args ...any) string {
	return NoBold(fmt.Sprintf(format, args...))
}

// Dim will Hilight() the provided string with the
// specified ANSI code.
func Dim(str string) string {
	return Hilight("dim", str)
}

// Dimf wraps fmt.Sprintf() and Dim.
func Dimf(format string, args ...any) string {
	return Dim(fmt.Sprintf(format, args...))
}

// NoDim will Hilight() the provided string with the
// specified ANSI code.
func NoDim(str string) string {
	return Hilight("nodim", str)
}

// NoDimf wraps fmt.Sprintf() and NoDim.
func NoDimf(format string, args ...any) string {
	return NoDim(fmt.Sprintf(format, args...))
}

// Faint will Hilight() the provided string with the
// specified ANSI code.
func Faint(str string) string {
	return Hilight("faint", str)
}

// Faintf wraps fmt.Sprintf() and Faint.
func Faintf(format string, args ...any) string {
	return Faint(fmt.Sprintf(format, args...))
}

// NoFaint will Hilight() the provided string with the
// specified ANSI code.
func NoFaint(str string) string {
	return Hilight("nofaint", str)
}

// NoFaintf wraps fmt.Sprintf() and NoFaint.
func NoFaintf(format string, args ...any) string {
	return NoFaint(fmt.Sprintf(format, args...))
}

// Italic will Hilight() the provided string with the
// specified ANSI code.
func Italic(str string) string {
	return Hilight("italic", str)
}

// Italicf wraps fmt.Sprintf() and Italic.
func Italicf(format string, args ...any) string {
	return Italic(fmt.Sprintf(format, args...))
}

// NoItalic will Hilight() the provided string with the
// specified ANSI code.
func NoItalic(str string) string {
	return Hilight("noitalic", str)
}

// NoItalicf wraps fmt.Sprintf() and NoItalic.
func NoItalicf(format string, args ...any) string {
	return NoItalic(fmt.Sprintf(format, args...))
}

// Underline will Hilight() the provided string with the
// specified ANSI code.
func Underline(str string) string {
	return Hilight("underline", str)
}

// Underlinef wraps fmt.Sprintf() and Underline.
func Underlinef(format string, args ...any) string {
	return Underline(fmt.Sprintf(format, args...))
}

// NoUnderline will Hilight() the provided string with the
// specified ANSI code.
func NoUnderline(str string) string {
	return Hilight("nounderline", str)
}

// NoUnderlinef wraps fmt.Sprintf() and NoUnderline.
func NoUnderlinef(format string, args ...any) string {
	return NoUnderline(fmt.Sprintf(format, args...))
}

// Blink will Hilight() the provided string with the
// specified ANSI code.
func Blink(str string) string {
	return Hilight("blink", str)
}

// Blinkf wraps fmt.Sprintf() and Blink.
func Blinkf(format string, args ...any) string {
	return Blink(fmt.Sprintf(format, args...))
}

// NoBlink will Hilight() the provided string with the
// specified ANSI code.
func NoBlink(str string) string {
	return Hilight("noblink", str)
}

// NoBlinkf wraps fmt.Sprintf() and NoBlink.
func NoBlinkf(format string, args ...any) string {
	return NoBlink(fmt.Sprintf(format, args...))
}

// BlinkSlow will Hilight() the provided string with the
// specified ANSI code.
func BlinkSlow(str string) string {
	return Hilight("blinkslow", str)
}

// BlinkSlowf wraps fmt.Sprintf() and BlinkSlow.
func BlinkSlowf(format string, args ...any) string {
	return BlinkSlow(fmt.Sprintf(format, args...))
}

// NoBlinkSlow will Hilight() the provided string with the
// specified ANSI code.
func NoBlinkSlow(str string) string {
	return Hilight("noblinkslow", str)
}

// NoBlinkSlowf wraps fmt.Sprintf() and NoBlinkSlow.
func NoBlinkSlowf(format string, args ...any) string {
	return NoBlinkSlow(fmt.Sprintf(format, args...))
}

// BlinkRapid will Hilight() the provided string with the
// specified ANSI code.
func BlinkRapid(str string) string {
	return Hilight("blinkrapid", str)
}

// BlinkRapidf wraps fmt.Sprintf() and BlinkRapid.
func BlinkRapidf(format string, args ...any) string {
	return BlinkRapid(fmt.Sprintf(format, args...))
}

// NoBlinkRapid will Hilight() the provided string with the
// specified ANSI code.
func NoBlinkRapid(str string) string {
	return Hilight("noblinkrapid", str)
}

// NoBlinkRapidf wraps fmt.Sprintf() and NoBlinkRapid.
func NoBlinkRapidf(format string, args ...any) string {
	return NoBlinkRapid(fmt.Sprintf(format, args...))
}

// Inverse will Hilight() the provided string with the
// specified ANSI code.
func Inverse(str string) string {
	return Hilight("inverse", str)
}

// Inversef wraps fmt.Sprintf() and Inverse.
func Inversef(format string, args ...any) string {
	return Inverse(fmt.Sprintf(format, args...))
}

// NoInverse will Hilight() the provided string with the
// specified ANSI code.
func NoInverse(str string) string {
	return Hilight("noinverse", str)
}

// NoInversef wraps fmt.Sprintf() and NoInverse.
func NoInversef(format string, args ...any) string {
	return NoInverse(fmt.Sprintf(format, args...))
}

// Negative will Hilight() the provided string with the
// specified ANSI code.
func Negative(str string) string {
	return Hilight("negative", str)
}

// Negativef wraps fmt.Sprintf() and Negative.
func Negativef(format string, args ...any) string {
	return Negative(fmt.Sprintf(format, args...))
}

// NoNegative will Hilight() the provided string with the
// specified ANSI code.
func NoNegative(str string) string {
	return Hilight("nonegative", str)
}

// NoNegativef wraps fmt.Sprintf() and NoNegative.
func NoNegativef(format string, args ...any) string {
	return NoNegative(fmt.Sprintf(format, args...))
}

// Swap will Hilight() the provided string with the
// specified ANSI code.
func Swap(str string) string {
	return Hilight("swap", str)
}

// Swapf wraps fmt.Sprintf() and Swap.
func Swapf(format string, args ...any) string {
	return Swap(fmt.Sprintf(format, args...))
}

// NoSwap will Hilight() the provided string with the
// specified ANSI code.
func NoSwap(str string) string {
	return Hilight("noswap", str)
}

// NoSwapf wraps fmt.Sprintf() and NoSwap.
func NoSwapf(format string, args ...any) string {
	return NoSwap(fmt.Sprintf(format, args...))
}

// Hide will Hilight() the provided string with the
// specified ANSI code.
func Hide(str string) string {
	return Hilight("hide", str)
}

// Hidef wraps fmt.Sprintf() and Hide.
func Hidef(format string, args ...any) string {
	return Hide(fmt.Sprintf(format, args...))
}

// NoHide will Hilight() the provided string with the
// specified ANSI code.
func NoHide(str string) string {
	return Hilight("nohide", str)
}

// NoHidef wraps fmt.Sprintf() and NoHide.
func NoHidef(format string, args ...any) string {
	return NoHide(fmt.Sprintf(format, args...))
}

// Conceal will Hilight() the provided string with the
// specified ANSI code.
func Conceal(str string) string {
	return Hilight("conceal", str)
}

// Concealf wraps fmt.Sprintf() and Conceal.
func Concealf(format string, args ...any) string {
	return Conceal(fmt.Sprintf(format, args...))
}

// NoConceal will Hilight() the provided string with the
// specified ANSI code.
func NoConceal(str string) string {
	return Hilight("noconceal", str)
}

// NoConcealf wraps fmt.Sprintf() and NoConceal.
func NoConcealf(format string, args ...any) string {
	return NoConceal(fmt.Sprintf(format, args...))
}

// CrossedOut will Hilight() the provided string with the
// specified ANSI code.
func CrossedOut(str string) string {
	return Hilight("crossedout", str)
}

// CrossedOutf wraps fmt.Sprintf() and CrossedOut.
func CrossedOutf(format string, args ...any) string {
	return CrossedOut(fmt.Sprintf(format, args...))
}

// NoCrossedOut will Hilight() the provided string with the
// specified ANSI code.
func NoCrossedOut(str string) string {
	return Hilight("nocrossedout", str)
}

// NoCrossedOutf wraps fmt.Sprintf() and NoCrossedOut.
func NoCrossedOutf(format string, args ...any) string {
	return NoCrossedOut(fmt.Sprintf(format, args...))
}

// Strikethrough will Hilight() the provided string with the
// specified ANSI code.
func Strikethrough(str string) string {
	return Hilight("strikethrough", str)
}

// Strikethroughf wraps fmt.Sprintf() and Strikethrough.
func Strikethroughf(format string, args ...any) string {
	return Strikethrough(fmt.Sprintf(format, args...))
}

// NoStrikethrough will Hilight() the provided string with the
// specified ANSI code.
func NoStrikethrough(str string) string {
	return Hilight("nostrikethrough", str)
}

// NoStrikethroughf wraps fmt.Sprintf() and NoStrikethrough.
func NoStrikethroughf(format string, args ...any) string {
	return NoStrikethrough(fmt.Sprintf(format, args...))
}

// Fraktur will Hilight() the provided string with the
// specified ANSI code.
func Fraktur(str string) string {
	return Hilight("fraktur", str)
}

// Frakturf wraps fmt.Sprintf() and Fraktur.
func Frakturf(format string, args ...any) string {
	return Fraktur(fmt.Sprintf(format, args...))
}

// NoFraktur will Hilight() the provided string with the
// specified ANSI code.
func NoFraktur(str string) string {
	return Hilight("nofraktur", str)
}

// NoFrakturf wraps fmt.Sprintf() and NoFraktur.
func NoFrakturf(format string, args ...any) string {
	return NoFraktur(fmt.Sprintf(format, args...))
}

// Hexf wraps fmt.Sprintf() and Hex.
func Hexf(hex string, format string, args ...any) string {
	return Hex(hex, fmt.Sprintf(format, args...))
}

// Hilightf wraps fmt.Sprintf() and Hilight.
func Hilightf(code string, format string, args ...any) string {
	return Hilight(code, fmt.Sprintf(format, args...))
}

// Hilightsf wraps fmt.Sprintf() and Hilights.
func Hilightsf(codes []string, format string, args ...any) string {
	return Hilights(codes, fmt.Sprintf(format, args...))
}

// OnHexf wraps fmt.Sprintf() and OnHex.
func OnHexf(hex string, format string, args ...any) string {
	return OnHex(hex, fmt.Sprintf(format, args...))
}

// OnRainbowf wraps fmt.Sprintf() and OnRainbow.
func OnRainbowf(format string, args ...any) string {
	return OnRainbow(fmt.Sprintf(format, args...))
}

// Plainf wraps fmt.Sprintf() and Plain.
func Plainf(format string, args ...any) string {
	return Plain(fmt.Sprintf(format, args...))
}

// Rainbowf wraps fmt.Sprintf() and Rainbow.
func Rainbowf(format string, args ...any) string {
	return Rainbow(fmt.Sprintf(format, args...))
}

// Wrapf wraps fmt.Sprintf() and Wrap.
func Wrapf(width int, format string, args ...any) string {
	return Wrap(width, fmt.Sprintf(format, args...))
}
